window.units = {
  length: [
    { value: "millimeter", label: "Millimeter (mm)" },
    { value: "centimeter", label: "Centimeter (cm)" },
    { value: "meter", label: "Meter (m)" },
    { value: "kilometer", label: "Kilometer (km)" },
    { value: "inch", label: "Inch (in)" },
    { value: "foot", label: "Foot (ft)" },
    { value: "yard", label: "Yard (yd)" },
    { value: "mile", label: "Mile (mi)" },
  ],
  mass: [
    { value: "milligram", label: "Milligram (mg)" },
    { value: "gram", label: "Gram (g)" },
    { value: "kilogram", label: "Kilogram (kg)" },
    { value: "tonne", label: "Tonne (t)" },
    { value: "ounce", label: "Ounce (oz)" },
    { value: "pound", label: "Pound (lb)" },
  ],
  temperature: [
    { value: "celsius", label: "Celsius (°C)" },
    { value: "fahrenheit", label: "Fahrenheit (°F)" },
    { value: "kelvin", label: "Kelvin (K)" },
    { value: "rankine", label: "Rankine (°R)" },
  ],
  speed: [
    { value: "mps", label: "Meter/second (m/s)" },
    { value: "kph", label: "Kilometer/hour (km/h)" },
    { value: "mph", label: "Mile/hour (mph)" },
    { value: "knot", label: "Knot (kn)" },
  ],
  volume: [
    { value: "ml", label: "Milliliter (mL)" },
    { value: "liter", label: "Liter (L)" },
    { value: "cubic_meter", label: "Cubic meter (m³)" },
    { value: "gallon", label: "Gallon (gal)" },
    { value: "pint", label: "Pint (pt)" },
  ],
  area: [
    { value: "sq_meter", label: "Square meter (m²)" },
    { value: "sq_kilometer", label: "Square kilometer (km²)" },
    { value: "sq_mile", label: "Square mile (mi²)" },
    { value: "sq_yard", label: "Square yard (yd²)" },
    { value: "sq_foot", label: "Square foot (ft²)" },
    { value: "hectare", label: "Hectare (ha)" },
    { value: "acre", label: "Acre (ac)" },
  ],
  time: [
    { value: "second", label: "Second (s)" },
    { value: "minute", label: "Minute (min)" },
    { value: "hour", label: "Hour (h)" },
    { value: "day", label: "Day (d)" },
    { value: "week", label: "Week (wk)" },
    { value: "year", label: "Year (yr)" },
  ],
  frequency: [
    { value: "hertz", label: "Hertz (Hz)" },
    { value: "kilohertz", label: "Kilohertz (kHz)" },
    { value: "megahertz", label: "Megahertz (MHz)" },
    { value: "gigahertz", label: "Gigahertz (GHz)" },
  ],
  angle: [
    { value: "degree", label: "Degree (°)" },
    { value: "radian", label: "Radian (rad)" },
    { value: "gradian", label: "Gradian (gon)" },
  ],
  force: [
    { value: "newton", label: "Newton (N)" },
    { value: "kilonewton", label: "Kilonewton (kN)" },
    { value: "dyne", label: "Dyne (dyn)" },
    { value: "pound_force", label: "Pound-force (lbf)" },
  ],
  pressure: [
    { value: "pascal", label: "Pascal (Pa)" },
    { value: "bar", label: "Bar" },
    { value: "psi", label: "Pound/sq.inch (psi)" },
    { value: "atm", label: "Atmosphere (atm)" },
    { value: "torr", label: "Torr (mmHg)" },
  ],
  energy: [
    { value: "joule", label: "Joule (J)" },
    { value: "kilojoule", label: "Kilojoule (kJ)" },
    { value: "calorie", label: "Calorie (cal)" },
    { value: "kilocalorie", label: "Kilocalorie (kcal)" },
    { value: "watt_hour", label: "Watt-hour (Wh)" },
    { value: "kilowatt_hour", label: "Kilowatt-hour (kWh)" },
  ],
  power: [
    { value: "watt", label: "Watt (W)" },
    { value: "kilowatt", label: "Kilowatt (kW)" },
    { value: "horsepower", label: "Horsepower (hp)" },
  ],
  electric_current: [
    { value: "ampere", label: "Ampere (A)" },
    { value: "milliampere", label: "Milliampere (mA)" },
  ],
  voltage: [
    { value: "volt", label: "Volt (V)" },
    { value: "millivolt", label: "Millivolt (mV)" },
    { value: "kilovolt", label: "Kilovolt (kV)" },
  ],
  resistance: [
    { value: "ohm", label: "Ohm (Ω)" },
    { value: "kiloohm", label: "Kiloohm (kΩ)" },
    { value: "megaohm", label: "Megaohm (MΩ)" },
  ],
  digital_storage: [
    { value: "bit", label: "Bit (b)" },
    { value: "byte", label: "Byte (B)" },
    { value: "kilobyte", label: "Kilobyte (KB)" },
    { value: "megabyte", label: "Megabyte (MB)" },
    { value: "gigabyte", label: "Gigabyte (GB)" },
    { value: "terabyte", label: "Terabyte (TB)" },
  ],
  fuel_consumption: [
    { value: "km_per_liter", label: "Kilometer/liter (km/L)" },
    { value: "liter_per_100km", label: "Liter/100km (L/100km)" },
    { value: "mpg", label: "Miles/gallon (mpg)" },
  ],
};
